using System;
using System.Collections;
using System.Collections.Generic;

namespace SharpScan
{
    public static class Configuration
    {

        public static Dictionary<string, List<string>> UserDictionary = new Dictionary<string, List<string>>
        {
            { "ftp", new List<string> { "ftp", "admin", "ftpuser", "www", "web", "root", "db", "wwwroot", "data",  } },
            { "mysql", new List<string> { "root", "mysql" } },
            { "mssql", new List<string> { "sa", "sql" } },
            { "smb", new List<string> { "administrator", "admin", "guest", "Lenovo" } },
            { "rdp", new List<string> { "administrator", "admin", "guest" ,"Lenovo"} },
            { "postgresql", new List<string> { "postgres", "admin" } },
            { "ssh", new List<string> { "root", "admin" } },
            { "mongodb", new List<string> { "root", "admin" } },
            { "oracle", new List<string> { "sys", "system", "admin", "test", "web", "orcl" } }
        };

        public static List<string> Passwords = new List<string>
        {
            
            "123456", "admin", "admin123", "root", "", "pass123", "pass@123", "password", "123123", "654321",
            "111111", "123", "1", "admin@123", "Admin@123", "admin123!@#", "{user}", "{user}1", "{user}111",
            "{user}123", "{user}@123", "{user}_123", "{user}#123", "{user}@111", "{user}@2019", "{user}@123#4",
            "P@ssw0rd!", "P@ssw0rd", "Passw0rd", "qwe123", "12345678", "test", "test123", "123qwe", "123qwe!@#",
            "123456789", "123321", "666666", "a123456.", "123456~a", "123456!a", "000000", "1234567890", "8888888","abc123$%",
            "!QAZ2wsx", "1qaz2wsx", "abc123", "abc123456", "1qaz@WSX", "a11111", "a12345", "Aa1234", "Aa1234.",
            "Aa12345", "a123456", "a123123", "Aa123123", "Aa123456", "Aa12345.", "sysadmin", "system", "1qaz!QAZ","Admin12345",
            "2wsx@WSX", "qwe123!@#", "Aa123456!", "A123456s!", "sa123456", "1q2w3e", "Charge123", "Aa123456789","a","admin!@#45","abc123$%"
        };

        //public static Dictionary<string, int> PortList = new Dictionary<string, int>
        //{
        //    { "ftp", 21 }, { "ssh", 22 }, { "findnet", 135 }, { "netbios", 139 }, { "smb", 445 },
        //    { "mssql", 1433 }, { "oracle", 1521 }, { "mysql", 3306 }, { "rdp", 3389 }, { "psql", 5432 },
        //    { "redis", 6379 }, { "fcgi", 9000 }, { "mem", 11211 }, { "mgo", 27017 },
        //    { "ms17010", 1000001 }, { "cve20200796", 1000002 }, { "web", 1000003 },
        //    { "webonly", 1000003 }, { "webpoc", 1000003 }, { "smb2", 1000004 }, { "wmiexec", 1000005 },
        //    { "all", 0 }, { "portscan", 0 }, { "icmp", 0 }, { "main", 0 }
        //};
        public static Dictionary<string, int> PortList = new Dictionary<string, int>
        {
            { "ftp", 21 }, { "ssh", 22 }, { "telnet", 23 }, { "smtp", 25 },
            { "dns", 53 }, { "http", 80 }, { "pop3", 110 }, { "ntp", 123 },{ "nbns", 137 },
            { "imap", 143 }, { "snmp", 161 }, { "ldap", 389 }, { "https", 443 },
            { "smb", 445 }, { "mssql", 1433 }, { "oracle", 1521 }, { "mysql", 3306 },
            { "rdp", 3389 }, { "psql", 5432 }, { "redis", 6379 }, { "fcgi", 9000 },
            { "mem", 11211 }, { "mgo", 27017 }, { "vnc", 5900 }, { "sip", 5060 },
            { "mqtt", 1883 }, { "nfs", 2049 }, { "msrpc", 135 }, { "nbss", 139 },{ "nbds", 138 },
            { "rpcbind", 111 }, { "snmptrap", 162 }, { "syslog", 514 }, { "tftp", 69 },
            { "kerberos", 88 }, { "smtps", 465 }, { "imaps", 993 }, { "pop3s", 995 },
            { "socks", 1080 }, { "ldaps", 636 }, { "ftps", 990 }, { "nntp", 119 },
            { "rsh", 514 }, { "exec", 512 }, { "login", 513 }, { "printer", 515 },
            { "nntps", 563 }, { "rtsp", 554 }, { "sip-tls", 5061 }, { "cifs", 3020 },
            { "msp", 18 }, { "bgp", 179 }, { "isakmp", 500 }, { "ldp", 646 },
            { "kpasswd", 464 }, { "submissions", 587 }, { "ircd", 6667 }, { "afs", 7000 },
            { "kerberos-adm", 749 }, { "kerberos-sec", 750 }, { "kerberos-pwd", 751 },
            { "klogin", 543 }, { "kshell", 544 }, { "knetd", 2053 }, { "dhcpv6-client", 546 },
            { "dhcpv6-server", 547 }, { "ntalk", 518 }, { "rtelnet", 107 }, { "sip-tcp", 5061 },
            { "sip-udp", 5060 }, { "ftam", 62 }, { "nfa", 115 }, { "imap3", 220 },
            { "sqlnet", 1500 }, { "vxlan", 4789 }, { "cmip-agent", 164 }, { "cmip-man", 163 },
            { "rsync", 873 }, { "alt-https", 8443 }, { "oracle-oms", 1158 }, { "apple-sasl", 3659 }
        };


       
        public static Dictionary<string, string> PortGroup = new Dictionary<string, string>
        {
            { "ftp", "21" }, { "ssh", "22" }, { "findnet", "135" }, { "netbios", "139" }, { "smb", "445" },
            { "mssql", "1433" }, { "oracle", "1521" }, { "mysql", "3306" }, { "rdp", "3389" }, { "psql", "5432" },
            { "redis", "6379" }, { "fcgi", "9000" }, { "mem", "11211" }, { "mgo", "27017" },
            { "ms17010", "445" }, { "cve20200796", "445" },
            { "service", "21,22,135,139,445,1433,1521,3306,3389,5432,6379,9000,11211,27017" },
            { "db", "1433,1521,3306,5432,6379,11211,27017" },
            { "web", "80,81,82,83,84,85,86,87,88,89,90,91,92,98,99,443,800,801,808,880,888,889,1000,1010,1080,1081,1082,1099,1118,1888,2008,2020,2100,2375,2379,3000,3008,3128,3505,5555,6080,6648,6868,7000,7001,7002,7003,7004,7005,7007,7008,7070,7071,7074,7078,7080,7088,7200,7680,7687,7688,7777,7890,8000,8001,8002,8003,8004,8006,8008,8009,8010,8011,8012,8016,8018,8020,8028,8030,8038,8042,8044,8046,8048,8053,8060,8069,8070,8080,8081,8082,8083,8084,8085,8086,8087,8088,8089,8090,8091,8092,8093,8094,8095,8096,8097,8098,8099,8100,8101,8108,8118,8161,8172,8180,8181,8200,8222,8244,8258,8280,8288,8300,8360,8443,8448,8484,8800,8834,8838,8848,8858,8868,8879,8880,8881,8888,8899,8983,8989,9000,9001,9002,9008,9010,9043,9060,9080,9081,9082,9083,9084,9085,9086,9087,9088,9089,9090,9091,9092,9093,9094,9095,9096,9097,9098,9099,9100,9200,9443,9448,9800,9981,9986,9988,9998,9999,10000,10001,10002,10004,10008,10010,10250,12018,12443,14000,16080,18000,18001,18002,18004,18008,18080,18082,18088,18090,18098,19001,20000,20720,21000,21501,21502,28018,20880" },
            { "all", "1-65535" },
            { "main", "21,22,80,81,135,139,443,445,1433,1521,3306,5432,6379,7001,8000,8080,8089,9000,9200,11211,27017" }
        };


        public static string WebPort = "80,81,82,83,84,85,86,87,88,89,90,91,92,98,99,443,800,801,808,880,888,889,1000,1010,1080,1081,1082,1099,1118,1888,2008,2020,2100,2375,2379,3000,3008,3128,3505,5555,6080,6648,6868,7000,7001,7002,7003,7004,7005,7007,7008,7070,7071,7074,7078,7080,7088,7200,7680,7687,7688,7777,7890,8000,8001,8002,8003,8004,8006,8008,8009,8010,8011,8012,8016,8018,8020,8028,8030,8038,8042,8044,8046,8048,8053,8060,8069,8070,8080,8081,8082,8083,8084,8085,8086,8087,8088,8089,8090,8091,8092,8093,8094,8095,8096,8097,8098,8099,8100,8101,8108,8118,8161,8172,8180,8181,8200,8222,8244,8258,8280,8288,8300,8360,8443,8448,8484,8800,8834,8838,8848,8858,8868,8879,8880,8881,8888,8899,8983,8989,9000,9001,9002,9008,9010,9043,9060,9080,9081,9082,9083,9084,9085,9086,9087,9088,9089,9090,9091,9092,9093,9094,9095,9096,9097,9098,9099,9100,9200,9443,9448,9800,9981,9986,9988,9998,9999,10000,10001,10002,10004,10008,10010,10250,12018,12443,14000,16080,18000,18001,18002,18004,18008,18080,18082,18088,18090,18098,19001,20000,20720,21000,21501,21502,28018,20880";

        public static string DefaultPorts = "21,22,80,81,135,139,443,445,1433,1521,3306,5432,6379,7001,8000,8080,8089,9000,9200,11211,27017";


        public static Dictionary<string, string> EDRQueryDictionary = new Dictionary<string, string>(){
    {"tdimon.exe", "SysInternals TDI Monitor"},
    {"setloadorder.exe", "BitDefender Security Suite"},
    {"powerscan.exe", "integrated search technologies"},
    {"f-sched.exe", "F-Prot?Antivirus"},
    {"csinject.exe", "Symantec"},
    {"mmod.exe", "ezulainc"},
    {"iptray.exe", "Cisco AMP"},
    {"casc.exe", "CA Internet Security Suite 2009"},
    {"stopa.exe", "AntiVir Security Management Center Agent Module"},
    {"csfalconcontainer.exe", "CrowdStrike Falcon Sensor"},
    {"reportsvc.exe", "Symantec Reporting Service"},
    {"kavpfw.exe", "kaspersky"},
    {"pasystemtray.exe", "Panda"},
    {"bdss.exe", "BitDefender Security Suite"},
    {"leventmgr.exe", "Cisco Security Agent"},
    {"_avpcc.exe", "卡巴斯基"},
    {"navshcom.exe", "Norton Anti-Virus"},
    {"savui.exe", "Symantec"},
    {"securitycenter.exe", "Aluria Security Center"},
    {"autoup.exe", "AhnLab"},
    {"sweepnet.sweepsrv.sys.swnetsup.exe", "Sophos Anti-Virus"},
    {"datemanager.exe", "Date Manager"},
    {"pavsrv52.exe", "Panda Anti-Virus"},
    {"edr_sec_plan.exe", "深信服EDR Agent"},
    {"ehttpsrv.exe", "Nod32"},
    {"ravtray.exe", "Rising AntiVirus"},
    {"ydedr.exe", "腾讯云-云镜主机安全"},
    {"avgmsvr.exe", "AVG"},
    {"pavprsrv.exe", "Panda Internet Security"},
    {"kvmonxp.kxp", "Jiangmin AV and FW"},
    {"titanin.exe", "titanhide"},
    {"usbguard.exe", "USB Disk Security"},
    {"ixaptsvc.exe", "nProtect"},
    {"unthreat.exe", "unthreat杀毒"},
    {"icmon.exe", "Sophos Anti-Virus InterCheck activity monitor"},
    {"isntsysmonitor", "TrendMicro InterScan System Monitor"},
    {"csrss_tc.exe", "Atompark StaffCop"},
    {"ppinupdt.exe", "Protector Plus for Windows"},
    {"hipsmain.exe", "火绒安全软件"},
    {"guardxkickoff.exe", "GuardX"},
    {"vba32ecm.exe", "Vba32"},
    {"fih32.exe", "F-Secure Installation Launcher"},
    {"softmanager.exe", "360软件管家"},
    {"avgas.exe", "AVG"},
    {"sndsrvc.exe", "Symantec"},
    {"nvcod.exe", "Norman"},
    {"semsvc.exe", "Symantec"},
    {"fortiproxy.exe", "Fortinet Smart Security"},
    {"esafe.exe", "eSafe Protect"},
    {"swdsvc.exe", "Spyware_Doctor 5 from PC Tools"},
    {"frameworkservic", "McAfee Framework Services"},
    {"vba32ifs.exe", "Vba32"},
    {"gdfwsvc.exe", "G Data Internet Security 2007"},
    {"avkservice.exe", "G Data Internet Security 2007"},
    {"kavss.exe", "Kaspersky"},
    {"savfmselog.exe", "Symantec Mail Security"},
    {"freshclam.exe", "clamav"},
    {"dpps2.exe", "panicware"},
    {"patray.exe", "ahnlab安博士杀毒"},
    {"symcorpui.exe", "symantec(赛门铁克)"},
    {"masalert.exe", "McAfee AntiSpyware"},
    {"firetray.exe", "McAfee Desktop Firewall Traybar Helper"},
    {"ashserv.exe", "Avast"},
    {"avkwctl9.exe", "g data software ag"},
    {"coreserviceshell.exe", "Trend Micro Internet Security"},
    {"mpfagent.exe", "McAfee Personal Firewall"},
    {"swdoctor.exe", "sonicwall"},
    {"mgui.exe", "bullguard"},
    {"bhipssvc.exe", "Baidu AV"},
    {"umxpol.exe", "CA Internet Security Suite 2007"},
    {"pxeservice.exe", "Symantec"},
    {"pctav.exe", "pc tools antivirus"},
    {"zanda.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"caavcmdscan.exe", "CA Internet Security Suite 2007"},
    {"klwtblfs.exe", "Kaspersky"},
    {"f-prot95.exe", "F-Prot?Antivirus"},
    {"tbscan.exe", "thunderbyte"},
    {"emet_agent.exe", "emet"},
    {"opssvc.exe", "Quick Heal AntiVirus"},
    {"tscutynt.exe", "Omniquad Total Security 3.0.0"},
    {"useranalysis.exe", "EventTracker Console"},
    {"crssvc.exe", "Cybereason"},
    {"drwebcom.exe", "DrWeb Plesk COM for Windows"},
    {"spideragent.exe", "DrWeb Total Security"},
    {"pavsrv50.exe", "Panda Anti-Virus"},
    {"navwnt.exe", "Symantec"},
    {"vrvmon.exe", "VRV Security Software"},
    {"npfmsg.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"mantispm.exe", "ZoneAlarm Internet Security Suite 2007"},
    {"tfun.exe", "Threatfire"},
    {"schupd.exe", "TrendMicro"},
    {"bargains.exe", "exact advertising spyware"},
    {"atwsctsk.exe", "AhnLab V3 Internet Security"},
    {"pccclient.exe", "TrendMicro PC-cillin"},
    {"esecservice.exe", "GFI EndPointSecurity"},
    {"kavlotsingleton.exe", "Kaspersky Anti-Virus for Lotus Notes"},
    {"mcproxy.exe", "McAfee Internet Security Suite"},
    {"gdscan.exe", "G Data"},
    {"qclean.exe", "McAfee QuickClean"},
    {"wsctrl.exe", "火绒安全软件"},
    {"winroute.exe", "Kerio Winroute Firewall"},
    {"csinsm32.exe", "Symantec"},
    {"fprottray.exe", "F-PROT Antivirus"},
    {"avgcc32.exe", "AVG"},
    {"cleaner8.exe", "the cleaner杀毒"},
    {"symwsc.exe", "Symantec"},
    {"krbcc32s.exe", "CA Jinchen KILL / eTrust Antivirus"},
    {"emlproxy.exe", "Omniquad Total Security 3.0.0"},
    {"avgnsx.exe", "AVG Internet Security"},
    {"avwatchservice.exe", "virusfighter杀毒"},
    {"sedservice.exe", "Sophos Endpoint Defense Service"},
    {"mpsvc.exe", "Omniquad Total Security 3.0.0"},
    {"gcasnotice.exe", "Microsoft AntiSpyware Notifier Process"},
    {"lwdmserver.exe", "TrendMicro Infrastructure"},
    {"usbkiller.exe", "u盘杀毒专家"},
    {"fortiscan.exe", "Fortiscan"},
    {"blss.exe", "cblaster"},
    {"starta.exe", "AntiVir Security Management Center Agent Module"},
    {"lucallbackproxy.exe", "Symantec"},
    {"dbserv.exe", "Symantec"},
    {"outpostproinstall.exe", "Agnitum Outpost Firewall Pro"},
    {"escc.exe", "启明星辰天珣EDR Agent"},
    {"navdx.exe", "Norton Anti-Virus"},
    {"safedogupdatecenter.exe", "安全狗"},
    {"eeyeevnt.exe", "eEye Retina Digital Security"},
    {"rpcserv.exe", "McAfee"},
    {"safedogtray.exe", "安全狗"},
    {"psctrls.exe", "Panda Internet Security"},
    {"dolphincharge.e", "GoldenDolphin Chinese IDS"},
    {"bdswitch.exe", "bitdefender module"},
    {"inoweb.exe", "CA Jinchen Kill"},
    {"managementagentnt.exe", "Sophos Control Center"},
    {"vstskmgr.exe", "McAfee VirusScan Task Manager"},
    {"avgidswatcher.exe", "AVG 8.5 IDS"},
    {"rescue32.exe", "卡巴斯基互联网安全套装"},
    {"aawservice.exe", "Lavasoft Ad-Aware"},
    {"cmctrayicon.exe", "cmc杀毒"},
    {"avk.exe", "gdata安全防护软件"},
    {"rcsync.exe", "prizesurfer"},
    {"nwservice.exe", "Netwatch"},
    {"360safebox.exe", "360保险箱主程序"},
    {"checkup.exe", "Symantec"},
    {"vrv.exe", "VRV Security Software"},
    {"ncdaemon.exe", "Mcafee Scanner for Lotus Notes"},
    {"unvet32.exe", "CA Internet Security Suite 2007"},
    {"avesvc.exe", "Avira"},
    {"mcuicnt.exe", "McAfee"},
    {"cleanup.exe", "mcafee"},
    {"pop3trap.exe", "TrendMicro PC-cillin"},
    {"knownsvr.exe", "Rising Antispyware"},
    {"pcciomon.exe", "pc-cillin"},
    {"fshoster32.exe", "F-Secure Internet Security"},
    {"hipsvc.exe", "mcafee"},
    {"cksoftshiedantivirus4.exe", "shield antivirus杀毒"},
    {"navapw32.exe", "Symantec"},
    {"kavfswp.exe", "Kaspersky Anti-Virus working process"},
    {"avgnsa.exe", "AVG Internet Security"},
    {"emet_service.exe", "emet"},
    {"avgupd.exe", "AVG"},
    {"defalert.exe", "symantec"},
    {"naprdmgr.exe", "McAfee ePolicy Orchestrator"},
    {"alunotify.exe", "Symantec"},
    {"fsorsp.exe", "F-Secure Internet Security"},
    {"psh_svc.exe", "Acronis Privacy Expert Suite"},
    {"sdhelp.exe", "spyware doctor"},
    {"kavadapterexe.exe", "Kaspersky Anti-Virus for Lotus Notes"},
    {"ccenter.exe", "Rising"},
    {"quhlpsvc.exe", "quickheal杀毒"},
    {"avgsystx.exe", "AVG SysTools"},
    {"sophossafestore64.exe", "Sophos Safestore Service"},
    {"pingscan.exe", "Ping Scanner"},
    {"kwsprod.exe", "Kaspersky"},
    {"ashquick.exe", "Avast"},
    {"ppppwallrun.exe", "Jiangmin AV and FW"},
    {"fcappdb.exe", "Fortinet Smart Security"},
    {"inocit.exe", "etrust"},
    {"sophososquery.exe", "Sophos杀毒"},
    {"websensecontrolservice.exe", "Websense Web Security / Web Filter"},
    {"aphost.exe", "TrendMicro Infrastructure"},
    {"snicheckadm.exe", "Secret Net"},
    {"kavshell.exe", "Kaspersky command line utility process"},
    {"spyemergencysrv.exe", "Netgate Spy Emergency"},
    {"mcupdmgr.exe", "McAfee Update Manager"},
    {"clpsls.exe", "Comodo"},
    {"cavscan.exe", "Comodo"},
    {"scfservice.exe", "Sophos FIREWALL"},
    {"safedogserverui.exe", "服务器安全狗"},
    {"pavfnsvr.exe", "Panda Internet Security"},
    {"parmor.exe", "木马克星"},
    {"v2iconsole.exe", "Symantec"},
    {"iparmor.exe", "木马克星"},
    {"clps.exe", "Comodo"},
    {"rtvscan.exe", "Symantec"},
    {"fp-win.exe", "f-prot antivirus ondemand"},
    {"fyfirewall.exe", "风云防火墙"},
    {"dlservice.exe", "SmartLine DeviceLock Service"},
    {"vprot.exe", "AVG VProtect Application for SafeSearch"},
    {"ashmaisv.exe", "Avast"},
    {"psimsvc.exe", "Panda Internet Security"},
    {"arr.exe", "application request route"},
    {"vrmonnt.exe", "hauri"},
    {"navectrl.exe", "Symantec"},
    {"esmagent.exe", "Enterprise Security Agent"},
    {"psctris.exe", "Panda Enterprise"},
    {"klnagent.exe", "Kaspersky Network Agent"},
    {"hwsd.exe", "护卫神·入侵防护系统"},
    {"aus.exe", "Outpost Security"},
    {"qhwebshellguard.exe", "360主机卫士"},
    {"capfaem.exe", "CA Internet Security Suite 2007"},
    {"sahookmain.exe", "McAfee SiteAdvisor"},
    {"sysdoc32.exe", "Symantec"},
    {"rsnetsvr.exe", "Rising Anti-Virus"},
    {"op_mon.exe", "outpostfirewall"},
    {"avgdiag.exe", "AVG"},
    {"mfeesp.exe", "McAfee Endpoint Security Platform component hosting server"},
    {"fsaua.exe", "F-Secure Internet Security"},
    {"defscangui.exe", "symantec"},
    {"mcepoc.exe", "McAfee VirusScan for EPOC OS"},
    {"fsavgui.exe", "F-Secure Internet Security GUI"},
    {"iamstats.exe", "symantec"},
    {"avkcl.exe", "gdata安全防护软件"},
    {"caunst.exe", "CA Internet Security Suite 2007"},
    {"patch.exe", "TrendMicro PC-cillin"},
    {"safedogsiteapache.exe", "网站安全狗(apache)"},
    {"kav32.exe", "Kingsoft Internet Security 2008"},
    {"hpqwmiex.exe", "HP ProtectTools Security Manager"},
    {"fsav530stbyb.exe", "f-secure"},
    {"savscan.exe", "Symantec"},
    {"tca.exe", "The Cleaner Active Process Monitor"},
    {"tnbutil.exe", "F-Secure Internet Security"},
    {"ekrn.exe", "Nod32"},
    {"avginet.exe", "AVG"},
    {"mcscript_inuse.exe", "McAfee VirusScan Enterprise"},
    {"bootwarn.exe", "symantec"},
    {"mskagent.exe", "McAfee SpamKiller Module"},
    {"cka.exe", "Symantec"},
    {"emlproui.exe", "Omniquad Total Security 3.0.0"},
    {"avastsvc.exe", "Avast"},
    {"iamapp.exe", "symantec"},
    {"vbcons.exe", "Vexira Antivirus Professional"},
    {"drwagnui.exe", "DrWeb"},
    {"navlu32.exe", "norton"},
    {"ccevtmgr.exe", "Symantec"},
    {"wfxmod32.exe", "Symantec"},
    {"tmproxy.exe", "TrendMicro PC-cillin"},
    {"savfmsespamstatsmanager.exe", "Symantec Mail Security"},
    {"mctray.exe", "McAfee VirusScan Enterprise"},
    {"umxfwhlp.exe", "CA Internet Security Suite 2007"},
    {"clpsla.exe", "Comodo"},
    {"saservice.exe", "McAfee Internet Security Suite"},
    {"scanningprocess.exe", "Kaspersky Antivirus Scanner"},
    {"vsserv.exe", "BitDefender Security Suite"},
    {"cloudhelper.exe", "安全狗"},
    {"supporter5.exe", "escorcher反病毒"},
    {"acaegmgr.exe", "AhnLab"},
    {"capmuamagt.exe", "CA eTrust Integrated Threat Management 8.1"},
    {"fsguidll.exe", "F-Secure Internet Security"},
    {"tc.exe", "timecalende"},
    {"calogdump.exe", "CA Internet Security Suite 2007"},
    {"sh.exe", "mks toolkit for win3"},
    {"guardnt.exe", "ikarus"},
    {"symsport.exe", "Symantec"},
    {"ccnfagent.exe", "CA eTrust Integrated Threat Management 8.1"},
    {"tfservice.exe", "ThreatFire PSP"},
    {"traptrackermgr.exe", "EventTracker SNMP Trap service"},
    {"qconsole.exe", "norton antivirus quarantine console"},
    {"sophosfimservice.exe", "Sophos FIM"},
    {"mbamtray.exe", "Malwarebytes Anti-Malware"},
    {"ngserver.exe", "Symantec"},
    {"fws.exe", "Radialpoint Security Services PCGuard"},
    {"gdfirewalltray.exe", "G Data Internet Security 2007"},
    {"spbbcsvc.exe", "Symantec"},
    {"brasil.exe", "exact advertising"},
    {"execstat.exe", "StatWin"},
    {"drwatson.exe", "Dr. Watson"},
    {"360safe.exe", "360安全卫士"},
    {"networx.exe", "NetWorx"},
    {"myagtsvc.exe", "mcafee"},
    {"spidercpl.exe", "dr.web"},
    {"aliyun_assist_service.exe", "阿里云-云监控"},
    {"swnetsup.exe", "Sophos Anti-Virus"},
    {"slee81.exe", "Steganos Security Suite Component"},
    {"scftray.exe", "Sophos FIREWALL"},
    {"mcui32.exe", "Symantec"},
    {"pop3pack.exe", "TrendMicro PC-cillin"},
    {"ndd32.exe", "诺顿磁盘医生"},
    {"vrmonsvc.exe", "hauri"},
    {"cfpsbmit.exe", "Comodo Firewall Pro"},
    {"aswupdsv.exe", "Avast"},
    {"mcsysmon.exe", "McAfee System Monitor"},
    {"bdagent.exe", "BitDefender Security Suite"},
    {"sophoscleanm.exe", "Sophos杀毒"},
    {"f-prot.exe", "f-prot杀毒"},
    {"pcscnsrv.exe", "TrendMicro"},
    {"navnt.exe", "Norton Anti-Virus"},
    {"kazza.exe", "kaspersky"},
    {"baiduansvx.exe", "百度卫士-主进程"},
    {"spiderui.exe", "DrWeb"},
    {"avkproxy.exe", "G Data Internet Security 2007"},
    {"mcwce.exe", "McAfee VirusScan for WindowsCE OS"},
    {"prizesurfer.exe", "prizesurfer"},
    {"msascuil.exe", "windows defender"},
    {"mcsclient.exe", "Sophos MCS Client"},
    {"ashpopwz.exe", "Avast"},
    {"avastemupdate.exe", "Avast Internet Security"},
    {"endpointsecurity.exe", "GFI EndPointSecurity"},
    {"webscanx.exe", "McAfee Web and ActiveX Scanner"},
    {"watchdog.exe", "Mustek"},
    {"mcconsol.exe", "McAfee VirusScan Enterprise"},
    {"cb.exe", "Cb Protection by Carbon Black"},
    {"vba32lder.exe", "vb32杀毒"},
    {"stwatchdog.exe", "TrendMicro ServerProtect"},
    {"lmon.exe", "Sophos Anti-Virus"},
    {"vettray.exe", "eTrust"},
    {"bpc.exe", "grokster"},
    {"avgam.exe", "AVG 8/8.5"},
    {"bkavsystemserver.exe", "Bkav AV"},
    {"ca.exe", "eTrust Firewall"},
    {"mcsagent.exe", "Sophos MCS Agent"},
    {"kpfw32.exe", "Kingsoft Internet Security 2008"},
    {"mcagent.exe", "McAfee Agent"},
    {"pylumloader.exe", "Cybereason"},
    {"sweep95.exe", "Sophos Anti-Virus"},
    {"fsdfwd.exe", "F-Secure Internet Security"},
    {"cfplogvw.exe", "Comodo Firewall Pro"},
    {"defenderdaemon.exe", "shadowdefender"},
    {"pestpatrol.exe", "ikarus"},
    {"nerosvc.exe", "Nero Security Service"},
    {"pthosttr.exe", "HP Protecttools Security Manager"},
    {"escccontrol.exe", "启明星辰天珣EDR Agent"},
    {"smsesrv.exe", "Symantec"},
    {"kavpf.exe", "kaspersky"},
    {"rfwstub.exe", "Rising"},
    {"zhudongfangyu.exe", "360主动防御"},
    {"pshost.exe", "Panda Internet Security"},
    {"navelog.exe", "Symantec"},
    {"qqpcrtp.exe", "腾讯电脑管家"},
    {"avgctrl.exe", "AVG"},
    {"smex_master.exe", "TrendMicro ScanMail for Exchange"},
    {"seanalyzertool.exe", "Netgate Spy Emergency"},
    {"ahnsdsv.exe", "AhnLab"},
    {"pavreport.exe", "Panda"},
    {"fnrb32.exe", "f-secure"},
    {"avgserv9.exe", "AVG"},
    {"lucoms~1.exe", "Symantec"},
    {"drweb.exe", "DrWeb"},
    {"safeweb.exe", "psafe tecnologia"},
    {"prmt.exe", "opistat"},
    {"avpdos32.exe", "kaspersky antivirus"},
    {"intdel.exe", "inet delivery"},
    {"etloganalyzer.exe", "EventTracker by Prism Microsystems"},
    {"inetupd.exe", "H+BEDV"},
    {"avg.exe", "avg杀毒"},
    {"bkavservice.exe", "bkav杀毒"},
    {"vrvnet.exe", "VRV Security Software"},
    {"secenter.exe", "bitdefender杀毒"},
    {"fspc.exe", "F-Secure Internet Security"},
    {"cdp.exe", "cyberlink corp."},
    {"webproxy.exe", "Panda Internet Security"},
    {"persfw.exe", "Kerio Personal Firewall 2.1.5"},
    {"capfasem.exe", "CA Internet Security Suite 2008"},
    {"fortifw.exe", "FortiClient Host Security 3.0.459"},
    {"seestat.exe", "StatWin"},
    {"sav32cli.exe", "Sophos Anti-Virus Scanner"},
    {"kavtray.exe", "Kaspersky task tray process"},
    {"printdevice.exe", "GoldenDolphin Chinese IDS"},
    {"bka.exe", "Bkav AV"},
    {"cavrid.exe", "CA AntiVirus Realtime Infection Report"},
    {"ucservice.exe", "Symantec"},
    {"fortiesnac.exe", "Fortinet Smart Security"},
    {"avgchsvx.exe", "AVG Internet Security"},
    {"avltmain.exe", "Panda Titanium"},
    {"pntiomon.exe", "TrendMicro PC-cillin"},
    {"cclgview.exe", "Symantec?"},
    {"mbamservice.exe", "Malwarebytes Anti-Malware"},
    {"aupdate.exe", "symantec"},
    {"basfipm.exe", "Broadcom ASF IP monitoring service"},
    {"nscsrvce.exe", "Symantec"},
    {"neowatchtray.exe", "neowatch"},
    {"blackice.exe", "BlackIce Firewall"},
    {"pavupg.exe", "Panda AdminSecure upgrade utility"},
    {"blackd.exe", "Black Ice IDS"},
    {"bwmeterconsvc.exe", "BWMeter Connections Service"},
    {"procexp.exe", "Sysinternals Process Explorer"},
    {"adaware.exe", "Lavasoft Ad-Aware"},
    {"ostronet.exe", "OstroSoft Internet Tools"},
    {"ngctw32.exe", "Symantec"},
    {"rb32.exe", "rapidblaster"},
    {"mcappins.exe", "McAfee Application Installer"},
    {"qhset.exe", "Quick Heal"},
    {"remupd.exe", "Panda Agent"},
    {"mcupdate.exe", "McAfee VirusScan Enterprise"},
    {"mfeavsvc.exe", "McAfee Cloud AV"},
    {"cfpconfg.exe", "COMODO VIRUS SCANNER"},
    {"kislive.exe", "Kingsoft"},
    {"padfsvr.exe", "Panda"},
    {"oespamtest.exe", "Kaspersky Anti-Spam for Outlook or Outlook Express"},
    {"cpf.exe", "Comodo Personal Firewall"},
    {"deteqt.agent.exe", "MWR Deteqt Suite EDR"},
    {"fast.exe", "fastusr"},
    {"trjscan.exe", "Simply Super Software Trojan Scanner"},
    {"swserver.exe", "StatWin Total"},
    {"v3exec.exe", "AhnLab V3 Internet Security"},
    {"repmgr64.exe", "Carbon Black"},
    {"inicio.exe", "Panda Internet Security"},
    {"mcmscsvc.exe", "McAfee Internet Security Suite"},
    {"ashsimpl.exe", "Avast"},
    {"ppclean.exe", "CA Internet Security Suite 2007"},
    {"pavw.exe", "Panda Internet Security"},
    {"retinaengine.exe", "eEye Retina Digital Security"},
    {"crashrep.exe", "Comodo Firewall Pro"},
    {"ntcadaemon.exe", "Huawei SACC Agent"},
    {"wrctrl.exe", "Kerio Winroute Firewall"},
    {"nlclient.exe", "Netlimiter Traffic Monitor"},
    {"nsctop.exe", "Symantec"},
    {"ravxp.exe", "Rising"},
    {"aexnsrcvsvc.exe", "Altiris"},
    {"kavfs.exe", "Kaspersky Anti-Virus service process"},
    {"nprotect.exe", "Symantec"},
    {"mcshell.exe", "McAfee GUI"},
    {"fortisslvpndaemon.exe", "Fortinet Smart Security"},
    {"acs.exe", "outpost防火墙"},
    {"avgwizfw.exe", "AVG"},
    {"seccenter.exe", "Bitdefender"},
    {"frw.exe", "McAfee?"},
    {"kvxp.kxp", "Jiangmin AV and FW"},
    {"savadminservice.exe", "Sophos Anti-Virus"},
    {"smsx.exe", "Security Technology Solutions SMSexpress"},
    {"mpfsrv.exe", "McAfee Internet Security Suite"},
    {"coranticontrolcenter32.exe", "coranti2012杀毒"},
    {"etscheduler.exe", "EventTracker Scheduler"},
    {"bwgo0000.exe", "F-Secure Backweb"},
    {"onlnsvc.exe", "Omniquad Total Security 3.0.0"},
    {"anti-trojan.exe", "anti-trojan elite"},
    {"cfpconfig.exe", "Comodo Firewall Pro"},
    {"kvxp.exe", "江民杀毒软件"},
    {"xagt.exe", "FireEye Endpoint Security"},
    {"nsmdemf.exe", "TrendMicro"},
    {"qserver.exe", "Symantec"},
    {"avgamsvr.exe", "AVG"},
    {"hws_ui.exe", "护卫神·入侵防护系统"},
    {"cctray.exe", "CA Internet Security Suite 2007"},
    {"msvxd.exe", "w32/datom-a"},
    {"uiseagnt.exe", "Trend Micro Internet Security"},
    {"fsav.exe", "f-secure"},
    {"etrssfeeds.exe", "EventTracker by Prism Microsystems"},
    {"klswd.exe", "Kaspersky"},
    {"comhost.exe", "Symantec"},
    {"ravalert.exe", "Rising AntiVirus"},
    {"vba32pp3.exe", "Vba32"},
    {"beagle.exe", "avast"},
    {"isafe.exe", "CA AntiVirus ISafe Service"},
    {"bdlite.exe", "BitDefender Security Suite"},
    {"avp.exe", "Kaspersky"},
    {"avpcc.exe", "Kaspersky"},
    {"aliyundunupdate.exe", "阿里云-升级服务"},
    {"showbehind.exe", "microsmarts enterprise component"},
    {"avptc32.exe", "kaspersky antivirus"},
    {"mbam.exe", "malwarebytes杀毒"},
    {"avserver.exe", "Kerio Winroute Firewall"},
    {"sms.exe", "Symantec"},
    {"ad-aware.exe", "Lavasoft Ad-Aware"},
    {"mcafeefire.exe", "mcafee"},
    {"cureit.exe", "drweb cureit"},
    {"dwwin.exe", "TrendMicro or DrWatson"},
    {"mfin32.exe", "myfreeinternetupdate"},
    {"defwatch.exe", "Symantec"},
    {"mfweng3.02d30.exe", "myfreeinternetupdate"},
    {"ravstub.exe", "Rising AntiVirus"},
    {"frameworkservic.exe", "Mcafee VirusScan Framework Service"},
    {"esccindex.exe", "启明星辰天珣EDR Agent"},
    {"ccregvfy.exe", "norton杀毒软件自身完整性检查程序"},
    {"scfmanager.exe", "Sophos FIREWALL"},
    {"avgcsrva.exe", "AVG Internet Security (64-bit)"},
    {"outpostinstall.exe", "outpost"},
    {"vrfwsvc.exe", "HAURI Firewall Service"},
    {"safedogguardcenter.exe", "安全狗"},
    {"ahnsd.exe", "AhnLab"},
    {"ezantivirusregistrationcheck.exe", "e-trust antivirus"},
    {"sophosfs.exe", "Sophos File Scanner Service"},
    {"avinitnt.exe", "command antivirus for nt server"},
    {"updaterui.exe", "McAfee VirusScan Enterprise"},
    {"bavtray.exe", "Baidu AV"},
    {"qdcsfs.exe", "Symantec"},
    {"avpdtagt.exe", "Kaspersky Lab Deployment Tool Agent"},
    {"gfireporterservice.exe", "GFI EndPointSecurity"},
    {"symproxysvc.exe", "Symantec"},
    {"ashbug.exe", "Avast"},
    {"infwin.exe", "msviewparasite"},
    {"trupd.exe", "Simply Super Software Trojan Scanner"},
    {"ashwebsv.exe", "Avast"},
    {"nod32view.exe", "NOD32 Update Viewer"},
    {"nvcoas.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"vprosvc.exe", "Symantec"},
    {"kvsrvxp_1.exe", "Jiangmin AV and FW"},
    {"pavss.exe", "熊猫卫士"},
    {"svdealer.exe", "SiliVaccine Antivirus"},
    {"monsvcnt.exe", "Ahnsd Korean AV"},
    {"avfwsvc.exe", "AVIRA Personal Edition Classic"},
    {"pfw.exe", "天网防火墙"},
    {"ghost_2.exe", "Symantec"},
    {"yunsuo_agent_service.exe", "云锁服务端"},
    {"ccpxysvc.exe", "Symantec"},
    {"bdsubmit.exe", "BitDefender Security Suite"},
    {"svcgenerichost.exe", "Trend Micro Worry-Free Business Security Services"},
    {"clshield.exe", "Panda"},
    {"apimonitor.exe", "API Monitor"},
    {"sbamsvc.exe", "Vipre"},
    {"smsesjm.exe", "Symantec"},
    {"nortonsecurity.exe", "Norton Security Deluxe"},
    {"masvc.exe", "McAfee Agent Service"},
    {"smsetask.exe", "Symantec"},
    {"savmain.exe", "Sophos Anti-Virus GUI is OPEN"},
    {"mscache.exe", "integrated search technologies spyware"},
    {"f-secure.exe", "f-secure冰岛杀毒"},
    {"ssscheduler.exe", "McAfee Security Scan"},
    {"pskmssvc.exe", "Panda Internet Security"},
    {"avmcdlg.exe", "Avira"},
    {"acaas.exe", "AhnLab"},
    {"protectx.exe", "protectx"},
    {"savfmsesp.exe", "Symantec"},
    {"smcgui.exe", "Symantec"},
    {"smex_remoteconf", "TrendMicro ScanMail for Exchange"},
    {"mfevtps.exe", "McAfee Process Validation"},
    {"uiwatchdog.exe", "Trend Micro Internet Security"},
    {"psuaservice.exe", "Panda Internet Security"},
    {"mfewc.exe", "McAfee Web Control Service"},
    {"avgmfapx.exe", "AVG Internet Security"},
    {"csinsmnt.exe", "Symantec"},
    {"guardgui.exe", "Avira"},
    {"vshwin32.exe", "McAfee On-access scanner"},
    {"zlclient.exe", "ZoneAlarm"},
    {"scanmsg.exe", "Omniquad Total Security 3.0.0"},
    {"pmon.exe", "Process Monitor"},
    {"kxescore.exe", "金山毒霸"},
    {"iswmgr.exe", "ZoneAlarm ForceField"},
    {"kaccore.exe", "Kingsoft"},
    {"gov_defence_daemon.exe", "govdefence(网防g01)"},
    {"ksafe.exe", "金山卫士"},
    {"netalertclient.exe", "GoldenDolphin Chinese IDS"},
    {"mpf.exe", "McAfee Personal Firewall"},
    {"sschk.exe", "Simply Super Software Trojan Scanner"},
    {"etagent.exe", "EventTracker by Prism Microsystems"},
    {"esav.exe", "启明星辰天珣EDR Agent"},
    {"vbcmserv.exe", "Vexira Antivirus Component Management Service"},
    {"amswmagt.exe", "CA eTrust Integrated Threat Management 8.1"},
    {"kupdata.exe", "金山毒霸"},
    {"aps.exe", "Outpost Security"},
    {"pccntupd.exe", "TrendMicro PC-cillin"},
    {"cssauth.exe", "Client Security Solution"},
    {"psuamain.exe", "Panda Internet Security"},
    {"mcinfo.exe", "McAfee Internet Security"},
    {"ad-watch.exe", "lavasoft杀毒"},
    {"clamwin.exe", "ClamAV"},
    {"cafw.exe", "CA Internet Security Suite 2007"},
    {"pavcl.exe", "Panda Commandline Secure"},
    {"avps.exe", "Kaspersky"},
    {"usrprmpt.exe", "Symantec"},
    {"aexswdusr.exe", "Altiris Express NS Client Manager"},
    {"scanwscs.exe", "Omniquad Total Security 3.0.0"},
    {"pcclient.exe", "TrendMicro PC-cillin"},
    {"ctdataload.exe", "Altiris"},
    {"luau.exe", "symantec"},
    {"sevinst.exe", "Symantec"},
    {"msscli.exe", "McAfee AntiSpyware Component"},
    {"kwsprotect64.exe", "金山毒霸"},
    {"nmagent.exe", "Network Monitor Agent"},
    {"wrsa.exe", "Webroot SecureAnywhere"},
    {"inort.exe", "eTrust Antivirus"},
    {"findviru.exe", "f-secure"},
    {"mfemms.exe", "McAfee Management Service"},
    {"almon.exe", "Sophos Anti-Virus"},
    {"vpc32.exe", "Symantec"},
    {"vsstat.exe", "McAfee VirusScan On-Access Scanner"},
    {"aesecurityservice.exe", "MS Content Management Service"},
    {"alisecguard.exe", "阿里云-云盾"},
    {"kav.exe", "Kaspersky"},
    {"avpncc.exe", "Kaspersky"},
    {"aavgapi.exe", "avg"},
    {"udaterui.exe", "McAfee VirusScan Enterprise"},
    {"appsvc32.exe", "Symantec"},
    {"snicon.exe", "Secret Net"},
    {"crdm.exe", "Netsys Enterprise Security (Encryption)"},
    {"egui.exe", "Nod32"},
    {"avgemc.exe", "AVG"},
    {"kansgui.exe", "Kingsoft Antivirus"},
    {"ns.exe", "norton诺顿杀毒"},
    {"mps.exe", "McAfee Internet Security Suite"},
    {"acaif.exe", "AhnLab"},
    {"mgavrtcl.exe", "McAfee antivirus software"},
    {"klserver.exe", "Kaspersky Administration Server"},
    {"cntaosmgr.exe", "TrendMicro OfficeScan"},
    {"pep.exe", "CA Jinchen KILL / eTrust Antivirus"},
    {"tsansrf.exe", "Omniquad Total Security 3.0.0"},
    {"pavsrv51.exe", "Panda Internet Security"},
    {"update_task.exe", "FortiClient Host Security 3.0.459"},
    {"ashenhcd.exe", "Avast"},
    {"mcwcecfg.exe", "McAfee VirusScan for WindowsCE OS"},
    {"ent.exe", "Essential NetTools"},
    {"fameh32.exe", "F-Secure Internet Security"},
    {"traflnsp.exe", "Traffic Inspector 2.0"},
    {"reportersvc.exe", "Symantec"},
    {"ccapp.exe", "Symantec"},
    {"tmlisten.exe", "TrendMicro PC-cillin"},
    {"regmech.exe", "Spyware Doctor"},
    {"tsatisy.exe", "Omniquad Total Security 3.0.0"},
    {"kmailmon.exe", "Kingsoft"},
    {"okclient.exe", "Cisco Security Agent"},
    {"avgnt.exe", "Avira"},
    {"drweb386.exe", "DrWeb"},
    {"prevsrv.exe", "Panda Anti-Virus"},
    {"a2start.exe", "Emsisoft Internet Security"},
    {"synmgr.exe", "sysmantec"},
    {"aswdisp.exe", "Avast"},
    {"kerio-pf-213-en-win.exe", "Kerio"},
    {"deep ui.exe", "Deep Instinct NGAV"},
    {"npfmsg2.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"pwdfilthelp.exe", "GoldenDolphin Chinese IDS"},
    {"casecuritycenter.exe", "CA Internet Security Suite 2007"},
    {"forticlient.exe", "FortiClient"},
    {"ccap.exe", "Symantec"},
    {"defwatch", "Symantec"},
    {"pxemtftp.exe", "Symantec"},
    {"ghosttray.exe", "Symantec"},
    {"asupport.exe", "TrendMicro"},
    {"sophosntpservice.exe", "Sophos杀毒"},
    {"spntsvc.exe", "TrendMicro ServerProtect"},
    {"jammer.exe", "Jammer"},
    {"vsmain.exe", "McAfee VirusScan Main Console"},
    {"msksrvr.exe", "McAfee Spamkiller"},
    {"csfalconservice.exe", "CrowdStrike Falcon"},
    {"360entclient.exe", "天擎EDR Agent"},
    {"ofcpfwsvc.exe", "TrendMicro Personal Firewall"},
    {"gzserv.exe", "Bitdefender Free"},
    {"fsmb32.exe", "F-Secure Internet Security"},
    {"atrshost.exe", "Altiris"},
    {"pccguide.exe", "TrendMicro PC-cillin"},
    {"fshdll32.exe", "F-Secure Internet Security"},
    {"avgsvc.exe", "AVG Internet Security"},
    {"wfxctl32.exe", "Symantec"},
    {"spiderml.exe", "DrWeb"},
    {"pavjobs.exe", "Panda Internet Security"},
    {"_avp32.exe", "卡巴斯基"},
    {"smex_systemwatc", "TrendMicro ScanMail for Exchange"},
    {"ppctlpriv.exe", "CA Internet Security Suite 2008 Antispyware"},
    {"360entmisc.exe", "360(奇安信)天擎"},
    {"aclient.exe", "Altiris remote login client"},
    {"fsav95.exe", "f-secure"},
    {"swnxt.exe", "Spyware Nuker"},
    {"fpavserver.exe", "F-PROT Antivirus"},
    {"ds_monitor.exe", "Deep Security TM EDR"},
    {"fsqh.exe", "F-Secure Internet Security"},
    {"drweb32.exe", "DrWeb"},
    {"smex_activeupda", "TrendMicro ScanMail for Exchange"},
    {"kavstart.exe", "Kingsoft Internet Security"},
    {"mpfservice.exe", "McAfee Personal Firewall Component"},
    {"msseces.exe", "Microsoft Security Essentials"},
    {"au.exe", "nsis"},
    {"ccemflsv.exe", "Client and Host Security Platform"},
    {"omslogmanager.exe", "Secret Net"},
    {"vpdn_lu.exe", "Symantec"},
    {"aawtray.exe", "Ad-Aware"},
    {"notifier.exe", "Deep Security TM EDR"},
    {"deloeminfs.exe", "BitDefender Security Suite"},
    {"emlibupdateagentnt.exe", "Sophos Control Center"},
    {"spidernt.exe", "DrWeb"},
    {"tpsrv.exe", "Panda Anti-Virus"},
    {"adam.exe", "绿鹰安全精灵"},
    {"smartscreen.exe", "windows defender smartscreen"},
    {"tanium.exe", "Tanium Client"},
    {"avengine.exe", "Panda Internet Security"},
    {"mongoosagui.exe", "mongoosa杀毒"},
    {"savservice.exe", "Sophos Anti-Virus"},
    {"zillya.exe", "Zillya Antivirus"},
    {"mcvsshld.exe", "McAfee VirusScan"},
    {"opscan.exe", "Symantec"},
    {"ndetect.exe", "Symantec"},
    {"prmvr.exe", "adtomi"},
    {"guarddog.exe", "ewido"},
    {"xagtnotif.exe", "FireEye Endpoint Security"},
    {"tclproc.exe", "ISS RealSecure IDS"},
    {"mcpalmcfg.exe", "McAfee VirusScan for Palm OS"},
    {"ast.exe", "超级巡警"},
    {"soap.exe", "system soap pro"},
    {"kpfwsvc.exe", "Kingsoft Internet Security"},
    {"lucomserver.exe", "Symantec LiveUpdate"},
    {"nymse.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"deepmgmtservice.exe", "Deep Instinct NGAV"},
    {"avwin.exe", "h+bedv"},
    {"avwupsrv.exe", "h+bedv"},
    {"realmon.exe", "CA Jinchen Kill Realtime Monitor"},
    {"mfemactl.exe", "McAfee Agent AAC Host"},
    {"qqpcnetflow.exe", "腾讯电脑管家"},
    {"ravupdate.exe", "Rising AntiVirus"},
    {"netcfg.exe", "Kaspersky Network Configuration Tool"},
    {"useractivity.exe", "EventTracker Scheduler"},
    {"pagentwd.exe", "Panda Enterprise"},
    {"umxagent.exe", "CA Internet Security Suite 2007"},
    {"avgcsrvx.exe", "AVG Internet Security"},
    {"ntrtscan.exe", "TrendMicro OfficeScan"},
    {"capfsem.exe", "CA Internet Security Suite 2007"},
    {"cfpupdat.exe", "Comodo Firewall Pro"},
    {"dsmain.exe", "360安全卫士程序加载模块"},
    {"smseui.exe", "Symantec"},
    {"baradagent.exe", "腾讯云-安全监控组件"},
    {"aexnsagent.exe", "Altiris Agent"},
    {"wfxsnt40.exe", "Symantec"},
    {"ashskpck.exe", "Avast"},
    {"pc.exe", "云锁客户端"},
    {"eguiproxy.exe", "eset nod32防毒"},
    {"cleaner3.exe", "windows流氓软件清理大师"},
    {"inouptng.exe", "etrust"},
    {"avgserv.exe", "AVG"},
    {"avgw.exe", "AVG"},
    {"ixavsvc.exe", "nProtect"},
    {"avciman.exe", "熊猫卫士"},
    {"nod32kui.exe", "Nod32"},
    {"avgscanx.exe", "AVG"},
    {"mscman.exe", "odysseusmarketinginc"},
    {"auth8021x.exe", "CA Jinchen KILL / eTrust Antivirus"},
    {"mcvsrte.exe", "McAfee.com VirusScan Online Realtime Engine"},
    {"mpcmdrun.exe", "Windows Defender"},
    {"aliyundun.exe", "阿里云-云盾"},
    {"vptray.exe", "Symantec System Tray Icon"},
    {"ofcdog.exe", "TrendMicro"},
    {"rfwsrv.exe", "Rising Firewall"},
    {"nslocollectorservice.exe", "enSilo Data Protection Collector Service"},
    {"prevx.exe", "Prevx"},
    {"ashdisp.exe", "Avast"},
    {"frameworkservice.exe", "McAfee VirusScan Enterprise"},
    {"scanmailoutlook.exe", "TrendMicro PC-cillin"},
    {"kpfwtray.exe", "金山网镖"},
    {"dbsrv9.exe", "Symantec"},
    {"gov_defence_service.exe", "govdefence(网防g01)"},
    {"cistray.exe", "Comodo Internet Security"},
    {"rtvscn95.exe", "real-time virus scanner"},
    {"vsmon.exe", "ZoneAlarm Component"},
    {"mcapexe.exe", "McAfee Endpoint Protection"},
    {"usergate.exe", "Entensys UserGate 5"},
    {"ewidoctrl.exe", "Ewido Security Suite"},
    {"kastray.exe", "Kingsoft"},
    {"isntsmtp.exe", "TrendMicro"},
    {"mcpromgr.exe", "McAfee Internet Security Suite"},
    {"edr_monitor.exe", "深信服EDR Agent"},
    {"mcdash.exe", "McAfee Security Center Dashboard"},
    {"issvc.exe", "Symantec"},
    {"mfeann.exe", "McAfee"},
    {"sndmon.exe", "Symantec"},
    {"bullguard.exe", "BullGuard Internet Security"},
    {"isuac.exe", "Symantec"},
    {"alogserv.exe", "McAfee VirusScan Activity Log Server"},
    {"pagent.exe", "Panda Enterprise"},
    {"tmpfw.exe", "TrendMicro"},
    {"pctsgui.exe", "Spyware Doctor"},
    {"zlh.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"mpmon.exe", "微点主动防御"},
    {"baidusdsvc.exe", "百度杀毒-服务进程"},
    {"pavbckpt.exe", "Panda Internet Security"},
    {"mpsevh.exe", "McAfee Internet Security Suite"},
    {"webtrap.exe", "Trend Micro"},
    {"nod32krn.exe", "Nod32"},
    {"mostat.exe", "wurldmediainc"},
    {"mcregwiz.exe", "McAfee Registration Wizard"},
    {"doscan.exe", "Symantec"},
    {"entitymain.exe", "Trend Micro Control Manager"},
    {"gcasswupdater.exe", "Microsoft AntiSpyware Updater Process"},
    {"svtray.exe", "SiliVaccine Antivirus"},
    {"pctstray.exe", "Spyware Doctor"},
    {"mfefire.exe", "McAfee Core Firewall Service"},
    {"mcepocfg.exe", "McAfee VirusScan for EPOC OS"},
    {"swagent.exe", "sonicwall"},
    {"ccsetmgr.exe", "Symantec"},
    {"qhonsvc.exe", "Quick Heal"},
    {"blink.exe", "micromedia"},
    {"rfwmain.exe", "Rising Firewall"},
    {"baidusdtray.exe", "百度杀毒-托盘进程"},
    {"ixfwsvc.exe", "nProtect"},
    {"mscifapp.exe", "McAfee Privacy Service"},
    {"msmgt.exe", "total velocity spyware"},
    {"safedogsiteiis.exe", "网站安全狗(iis)"},
    {"gcascleaner.exe", "Microsoft AntiSpyware Cleaner Process"},
    {"safedog.exe", "安全狗"},
    {"ccupdate.exe", "CA Internet Security Suite 2007"},
    {"zapro.exe", "ZoneAlarm IDS"},
    {"ashcmd.exe", "Avast"},
    {"sweepsrv.exe", "Sophos Anti-Virus"},
    {"kavisarv.exe", "Kaspersky"},
    {"certificationmanagerservicent.exe", "Sophos Control Center"},
    {"myagttry.exe", "McAfee Total Protection for Small Business"},
    {"webtrapnt.exe", "TrendMicro PC-cillin"},
    {"a2cmd.exe", "emsisoft anti-malware"},
    {"savfmsesrv.exe", "Symantec Mail Security"},
    {"k7tsecurity.exe", "k7杀毒"},
    {"tvmd.exe", "total velocity"},
    {"guardxservice.exe", "GuardX"},
    {"fprot.exe", "F-Prot?Antivirus"},
    {"sesclu.exe", "Symantec"},
    {"zonealarm.exe", "ZoneAlarm IDS"},
    {"drwupgrade.exe", "DrWeb Enterprise"},
    {"savprogress.exe", "Sophos杀毒"},
    {"dwarkdaemon.exe", "DrWeb Total Security"},
    {"ispwdsvc.exe", "Symantec"},
    {"evtprocessecfile.exe", "EventTracker"},
    {"toolbarupdater.exe", "AVG Internet Security (64-bit)"},
    {"alert.exe", "CA eTrust Integrated Threat Management 8.1/CA Jinchen Kill"},
    {"csacontrol.exe", "Cisco Security Agent"},
    {"pctssvc.exe", "Spyware Doctor"},
    {"ppvstop.exe", "PP2000 Real Time Scan"},
    {"aswscan.exe", "avast"},
    {"avgcc.exe", "AVG"},
    {"klnacserver.exe", "Kaspersky Lab Cisco NAC Posture Validation Server"},
    {"mpftray.exe", "McAfee Personal Firewall Tray icon"},
    {"ayagent.exe", "alyac韩国胶囊杀毒"},
    {"pavsched.exe", "Panda Anti-Virus"},
    {"hws.exe", "护卫神·入侵防护系统"},
    {"navw32.exe", "Symantec"},
    {"ntcaservice.exe", "Huawei SACC Agent"},
    {"bitdefender.exe", "Bitdefender"},
    {"avpm.exe", "Kaspersky"},
    {"kanmcmain.exe", "Kingsoft"},
    {"avmailc.exe", "Avira"},
    {"wdswfsafe.exe", "360杀毒-网盾"},
    {"armor2net.exe", "Armor2net Software"},
    {"neotrace.exe", "McAfee NeoTrace"},
    {"kvolself.exe", "Jiangmin AV and FW"},
    {"cmgrdian.exe", "McAfee Guardian Tray Icon"},
    {"tvtmd.exe", "total velocity"},
    {"kerio-wrl-421-en-win.exe", "Kerio"},
    {"uploadrecord.exe", "USB thumb drive security"},
    {"mcnasvc.exe", "McAfee Internet Security Suite"},
    {"console.exe", "Panda"},
    {"nip.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"fpwin.exe", "verizon"},
    {"ahprocmonserver.exe", "安天防线"},
    {"a2guard.exe", "a-squared杀毒"},
    {"rasupd.exe", "Rising Antispyware"},
    {"mghtml.exe", "McAfee VirusScan Component"},
    {"dltray.exe", "SmartLine DeviceLock Tray Notifier"},
    {"control_panel.exe", "Entensys UserGate 5"},
    {"aluschedulersvc.exe", "Symantec"},
    {"spybotsd.exe", "spybot"},
    {"ravmond.exe", "Rising AntiVirus"},
    {"npscheck.exe", "Symantec"},
    {"avgrsx.exe", "AVG Anti-Virus"},
    {"sfc.exe", "Cisco AMP"},
    {"beikesan.exe", "贝壳云安全"},
    {"vba32ldr.exe", "Vba32"},
    {"ydlive.exe", "腾讯云-云镜主机安全"},
    {"nrmenctb.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"navapsvc.exe", "Symantec"},
    {"tmas.exe", "TrendMicro Anti-Spyware"},
    {"agb.exe", "安天防线"},
    {"inorpc.exe", "eTrust Antivirus"},
    {"snhwsrv.exe", "Secret Net"},
    {"drwebcgp.exe", "DrWeb"},
    {"run32dll.exe", "pal pc spy"},
    {"clamscan.exe", "ClamAV"},
    {"dolphincharge.exe", "GoldenDolphin Chinese IDS"},
    {"drwadins.exe", "dr.web"},
    {"fwcfg.exe", "Symantec"},
    {"fssm32.exe", "F-Secure Internet Security"},
    {"monsysnt.exe", "Ahnsd Korean AV"},
    {"avgemca.exe", "AVG Internet Security"},
    {"atguard.exe", "antivir"},
    {"cramtray.exe", "Cybereason"},
    {"savfmsetask.exe", "Symantec Mail Security"},
    {"bullguardscanner.exe", "BullGuard Internet Security"},
    {"psanhost.exe", "Panda Internet Security"},
    {"avkbackupservice.exe", "gdata安全防护软件"},
    {"icepack.exe", "Symantec"},
    {"whoswatchingme.exe", "Who's Watching Me"},
    {"arcatasksservice.exe", "arcavir杀毒"},
    {"bdmcon.exe", "BitDefender Security Suite"},
    {"kerio-wrp-421-en-win.exe", "Kerio"},
    {"edr_agent.exe", "深信服EDR Agent"},
    {"usysdiag.exe", "火绒安全软件"},
    {"vpc42.exe", "symantec"},
    {"fch32.exe", "F-Secure Internet Security"},
    {"cfp.exe", "Comodo Firewall Pro"},
    {"aexagentuihost.exe", "Altiris Agent"},
    {"cylanceui.exe", "Cylance"},
    {"d_safe_manage.exe", "d盾"},
    {"kansvr.exe", "Kingsoft Antivirus"},
    {"uplive.exe", "Kingsoft"},
    {"nsmdsch.exe", "TrendMicro"},
    {"privacyiconclient.exe", "Intel Management and Security"},
    {"nav.exe", "reuters limited"},
    {"etcorrel.exe", "EventTracker log cache"},
    {"avpexec.exe", "Kaspersky"},
    {"knsdtray.exe", "可牛杀毒"},
    {"qhonline.exe", "Quick Heal Online Protection"},
    {"f-stopw.exe", "F-Prot?Antivirus"},
    {"proutil.exe", "BlackIce Firewall"},
    {"clamtray.exe", "ClamAV"},
    {"isntsysmonitor.exe", "Trend Micro"},
    {"neowatchlog.exe", "neowatch"},
    {"avpui.exe", "Kaspersky"},
    {"evtmgr.exe", "EventTracker by Prism Microsystems"},
    {"mrf.exe", "TrendMicro Infrastructure"},
    {"ad-aware2007.exe", "Lavasoft Ad-Aware"},
    {"msksrver.exe", "McAfee Internet Security Suite"},
    {"avgaurd.exe", "avira antivir"},
    {"svcntaux.exe", "Spyware_Doctor 5 from PC Tools"},
    {"mcsacore.exe", "McAfee Endpoint Protection"},
    {"op_viewer.exe", "Sophos FIREWALL GUI is OPEN"},
    {"caantispyware.exe", "CA Internet Security Suite 2007"},
    {"nmain.exe", "Symantec"},
    {"kissvc.exe", "Kingsoft Internet Security 2008"},
    {"pqibrowser.exe", "Symantec"},
    {"mssecess.exe", "Microsoft Security Essentials"},
    {"isscsf.exe", "ISS Security Scanner"},
    {"sgagent.exe", "腾讯云-安全监控组件"},
    {"engineserver.exe", "McAfee"},
    {"eventparser.exe", "McAfee"},
    {"connectionmonitor.exe", "ConnectionMonitor by SteelBytes"},
    {"atwatch.exe", "mustek"},
    {"avgfws.exe", "AVG Internet Security"},
    {"oasclnt.exe", "McAfee VirusScan Module"},
    {"mgntsvc.exe", "Sophos Control Center"},
    {"mctskshd.exe", "McAfee Task Scheduler"},
    {"baidusd.exe", "百度杀毒-主程序"},
    {"sophoscleanm64.exe", "Sophos Clean Service"},
    {"drwebwcl.exe", "DrWeb"},
    {"pview.exe", "Process Explode process viewer"},
    {"trojanhunter.exe", "木马猎手"},
    {"hwspanel.exe", "护卫神·入侵防护系统"},
    {"avsynmgr.exe", "McAfee VirusScan Synchronization Manager"},
    {"bullguardbhvscanner.exe", "BullGuard Internet Security"},
    {"avktray.exe", "G Data Internet Security 2007"},
    {"drwebscd.exe", "DrWeb"},
    {"mcshield.exe", "McAfee VirusScan"},
    {"nsmdreal.exe", "TrendMicro"},
    {"ssecuritymanager.exe", "SIWF BAM Services"},
    {"kvmonxp.exe", "江民杀毒"},
    {"spyemergency.exe", "Netgate Spy Emergency"},
    {"iface.exe", "Panda Anti-Virus"},
    {"idsinst.exe", "Symantec"},
    {"smsectrl.exe", "Symantec"},
    {"networkagent.exe", "Websense Web Security / Web Filter"},
    {"tbmon.exe", "McAfee VirusScan"},
    {"cavtray.exe", "eTrust Antivirus"},
    {"adminserver.exe", "Panda"},
    {"drwebdc.exe", "DrWeb"},
    {"mcvsftsn.exe", "McAfee VirusScan Online"},
    {"fsm32.exe", "F-Secure Internet Security"},
    {"pccpfw.exe", "TrendMicro PC-cillin"},
    {"avgtray.exe", "AVG Anti-Virus"},
    {"infus.exe", "infus dialer"},
    {"inonmsrv.exe", "CA Jinchen Kill"},
    {"drwebupw.exe", "DrWeb"},
    {"nipsvc.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"espwatch.exe", "eSafe Protect"},
    {"tftray.exe", "ThreatFire PSP"},
    {"bwgo0000", "F-Secure Backweb Temporary Files"},
    {"deepstaticservice.exe", "Deep Instinct NGAV"},
    {"isatray.exe", "Microsoft(R) Internet Security and Acceleration Server 2000"},
    {"caf.exe", "CA eTrust Integrated Threat Management 8.1"},
    {"yunsuo_agent_daemon.exe", "云锁服务端"},
    {"mfecanary.exe", "McAfee Canary Process"},
    {"cmdagent.exe", "Comodo Firewall Pro"},
    {"qqpcrealtimespeedup.exe", "腾讯电脑管家"},
    {"bmrt.exe", "Barracuda Malware Removal Tool"},
    {"avgcefrend.exe", "AVG Internet Security"},
    {"bddownloader.exe", "百度卫士"},
    {"cmdinstall.exe", "Comodo"},
    {"itmrt_trace.exe", "CA Internet Security Suite 2007"},
    {"drwebmng.exe", "DrWeb"},
    {"vpatch.exe", "ISS_Proventia_Agent 9.0 from IBM"},
    {"wimmun32.exe", "iRiS AntiVirus Active Monitor"},
    {"v3svc.exe", "AhnLab"},
    {"gcasserv.exe", "Microsoft AntiSpyware Server Process"},
    {"itmrtsvc.exe", "CA Internet Security Suite 2007"},
    {"rapapp.exe", "BlackIce Firewall"},
    {"avkwctl.exe", "G Data Internet Security 2007"},
    {"symtray.exe", "Symantec"},
    {"mspmspsv.exe", "Windows Media Device Manager Pre-Message Security Protocol Service"},
    {"srvload.exe", "Panda Internet Security"},
    {"symlcsvc.exe", "Symantec"},
    {"njeeves.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"caissdt.exe", "eTrust Internet Security Suite"},
    {"fsguiexe.exe", "F-Secure Internet Security"},
    {"360sd.exe", "360杀毒"},
    {"tmntsrv.exe", "TrendMicro PC-cillin"},
    {"mcsvhost.exe", "McAfee Endpoint Protection"},
    {"aswserv.exe", "Avast"},
    {"ccprovsp.exe", "CA Internet Security Suite 2008/9"},
    {"_avpm.exe", "卡巴斯基"},
    {"ssp.exe", "Sophos Endpoint Security"},
    {"outpost.exe", "Outpost Security"},
    {"360skylarsvc.exe", "360天擎终端安全管理系统"},
    {"wrspysetup.exe", "Super WinSpy"},
    {"drwagntd.exe", "DrWeb Enterprise"},
    {"sgbhp.exe", "SpywareBlaster Internet Security Tool"},
    {"sdrservice.exe", "Sophos Anti-Virus"},
    {"diskmon.exe", "Symantec"},
    {"a2service.exe", "a-squared free"},
    {"rulaunch.exe", "McAfee User Interface"},
    {"dssagent.exe", "broderbund"},
    {"nlsvc.exe", "LockTime NetLimiter 2 Monitor"},
    {"cappactiveprotection.exe", "CA Internet Security Suite 2007"},
    {"mfefw.exe", "McAfee Firewall Business Object Hosting Server"},
    {"system.exe", "LanAgent Monitoring"},
    {"itmrt_supportdiagnostics.exe", "CA Internet Security Suite 2007"},
    {"avnotify.exe", "Avira"},
    {"gziface.exe", "Bitdefender Free"},
    {"acais.exe", "AhnLab"},
    {"hrres.exe", "ViRobot Desktop Antivirus"},
    {"dwnetfilter.exe", "DrWeb Total Security"},
    {"log_qtine.exe", "McAfee"},
    {"luinit.exe", "Symantec"},
    {"siteadv.exe", "McAfee Internet Security Suite"},
    {"avgidsui.exe", "AVG 8.5 IDS"},
    {"v3medic.exe", "AhnLab"},
    {"cfd.exe", "motive communications"},
    {"msascui.exe", "Windows Defender"},
    {"xcommsvr.exe", "BitDefender Security Suite"},
    {"pcctlcom.exe", "TrendMicro"},
    {"fcdblog.exe", "Fortinet Smart Security"},
    {"mcmnhdlr.exe", "McAfee VirusScan Command Handler"},
    {"safeboxtray.exe", "360保险箱的托盘程序"},
    {"msmpeng.exe", "Windows Defender"},
    {"bullguardupdate.exe", "BullGuard Internet Security"},
    {"ethereal.exe", "rationalclearcase"},
    {"issdaemon.exe", "ISS Security Scanner"},
    {"knupdatemain.exe", "Kingsoft"},
    {"sysoptenginesvc.exe", "Baidu AV"},
    {"fsgk32.exe", "F-Secure Internet Security"},
    {"tsmpnt.exe", "Omniquad Total Security 3.0.0"},
    {"omniagent.exe", "MWR OmniAgent"},
    {"edisk.exe", "McAfee VirusScan Emergency Disk Creator"},
    {"gcasdtserv.exe", "Microsoft AntiSpyware Server Process"},
    {"kvsrvxp.exe", "Jiangmin AV and FW"},
    {"avkpop.exe", "g data software ag"},
    {"nailgpip.exe", "McAfee"},
    {"cylancesvc.exe", "Cylance"},
    {"alsvc.exe", "Sophos AutoUpdate Service"},
    {"ewidoguard.exe", "Ewido Security Suite"},
    {"mcuimgr.exe", "McAfee Internet Security Suite"},
    {"kb891711.exe", "Windows Security Update"},
    {"scanexplicit.exe", "Symantec"},
    {"qqpctray.exe", "腾讯电脑管家"},
    {"cfsmsmd.exe", "CA eTrust Integrated Threat Management 8.1"},
    {"amsvc.exe", "Cybereason"},
    {"fsgk32st.exe", "F-Secure Internet Security"},
    {"giantantispywareupdater.exe", "Microsoft AntiSpyware"},
    {"htpatch.exe", "silicon integrated systems corporation"},
    {"kxetray.exe", "金山毒霸"},
    {"anvir.exe", "AnVir.exe"},
    {"blupro.exe", "Bkav AV"},
    {"tfgui.exe", "Threatfire GUI"},
    {"pctsauxs.exe", "Spyware Doctor"},
    {"euqmonitor.exe", "TrendMicro ScanMail for Exchange"},
    {"spywareterminatorshield.exe", "spywareterminator杀毒"},
    {"kswebshield.exe", "Kingsoft"},
    {"etreporter.exe", "EventTracker by Prism Microsystems  change"},
    {"hipstray.exe", "火绒安全软件"},
    {"stopp.exe", "TrendMicro ServerProtect"},
    {"ashsimp2.exe", "Avast"},
    {"macmnsvc.exe", "McAfee Agent Common Services"},
    {"urllstck.exe", "Symantec"},
    {"ashupd.exe", "Avast"},
    {"sophosfilescanner.exe", "Sophos杀毒"},
    {"rcsvcmon.exe", "GFI EndPointSecurity"},
    {"clean.exe", "windows流氓软件清理大师"},
    {"coreframeworkhost.exe", "Trend Micro Internet Security"},
    {"navesp.exe", "Symantec"},
    {"v3imscn.exe", "AhnLab V3 Internet Security"},
    {"navstub.exe", "Norton Anti-Virus"},
    {"etwcontrolpanel.exe", "EventTracker Console"},
    {"aexsvc.exe", "Altiris"},
    {"srvmon.exe", "McAfee"},
    {"gcasservalert.exe", "Microsoft AntiSpyware Alert Process"},
    {"alertsvc.exe", "Symantec"},
    {"hipslog.exe", "火绒安全软件"},
    {"nisum.exe", "Symantec"},
    {"shstat.exe", "McAfee VirusScan Enterprise"},
    {"caav.exe", "CA Internet Security Suite 2007"},
    {"ssm.exe", "Symantec or Veritas Net Backup"},
    {"massrv.exe", "McAfee AntiSpyware application"},
    {"amon.exe", "tiny personal firewall"},
    {"avscan.exe", "Avira"},
    {"fsaa.exe", "F-Secure Authentication Agent"},
    {"qhsrv.exe", "360主机卫士"},
    {"wscntfy.exe", "Microsoft Windows Security Center"},
    {"pccntmon.exe", "TrendMicro PC-cillin"},
    {"avgfws9.exe", "AVG 9.0 FW"},
    {"kvmonxp_2.exe", "江民KV杀毒软件实时监控程序"},
    {"ldscan.exe", "windows trojans inspector"},
    {"mskdetct.exe", "McAfee Spamkiller"},
    {"esecagntservice.exe", "GFI EndPoint Security"},
    {"igateway.exe", "CA eTrust Integrated Threat Management 8.1/CA Jinchen Kill"},
    {"kavsvcui.exe", "kaspersky"},
    {"sphinx.exe", "sphinx防火墙"},
    {"proport.exe", "ProPort"},
    {"mcshld9x.exe", "McAfee AntiVirus Component"},
    {"bdc.exe", "BitDefender Security Suite"},
    {"avgidsmonitor.exe", "AVG 8.5/9.0 IDS"},
    {"emsw.exe", "alset inc"},
    {"pnmsrv.exe", "Panda Network Manager"},
    {"updtnv28.exe", "Symantec"},
    {"umxcfg.exe", "CA Internet Security Suite 2007"},
    {"liveupdate360.exe", "360更新程序"},
    {"snsrv.exe", "Secret Net"},
    {"mcscript.exe", "mcafee"},
    {"ravtask.exe", "Rising AntiVirus"},
    {"cfftplugin.exe", "CA eTrust Integrated Threat Management 8.1"},
    {"xfilter.exe", "Omniquad Total Security 3.0.0"},
    {"sdcservice.exe", "Sophos Device Control Service"},
    {"protectedmodulehost.exe", "McAfee"},
    {"rfwproxy.exe", "Rising"},
    {"rnreport.exe", "Rising AntiVirus"},
    {"avcenter.exe", "Avira"},
    {"npfsvice.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"pavmail.exe", "Panda Anti-Virus"},
    {"kxeserv.exe", "Kingsoft"},
    {"avgregcl.exe", "AVG Registry Cleaner"},
    {"cleaner.exe", "windows流氓软件清理大师"},
    {"avpupd.exe", "Kaspersky"},
    {"360leakfixer.exe", "360系统漏洞控制模块"},
    {"fortiwf.exe", "Fortinet Smart Security"},
    {"pavproxy.exe", "熊猫卫士"},
    {"ccsvchst.exe", "Symantec Endpoint Protection"},
    {"pavkre.exe", "Panda Anti-Virus"},
    {"securitymanager.exe", "MSC BAM Services"},
    {"swc_service.exe", "Sophos Anti-Virus"},
    {"svcgenerichost", "TrendMicro ScanMail for Exchange"},
    {"isafinst.exe", "CA Internet Security Suite 2007"},
    {"eshasrv.exe", "eset nod32防毒"},
    {"airdefense.exe", "airdefense"},
    {"luall.exe", "Symantec"},
    {"rapuisvc.exe", "ISS_Proventia_Agent 9.0 from IBM"},
    {"kvdetech.exe", "Jiangmin AV and FW"},
    {"kwatch.exe", "Kingsoft Internet Security"},
    {"sidebar.exe", "AVG Anti-Virus"},
    {"qoeloader.exe", "Qurb/CA Internet Security 2008/9 AntiSpam"},
    {"pgmonitr.exe", "promulgate spyware"},
    {"avshadow.exe", "Avira"},
    {"winlog.exe", "Salfeld Personal Security Manager"},
    {"livesrv.exe", "BitDefender Security Suite"},
    {"aswwebsv.exe", "Avast"},
    {"avtask.exe", "Panda"},
    {"mfehcs.exe", "McAfee HookCore Service"},
    {"fortitray.exe", "Fortinet Smart Security"},
    {"giantantispywaremain.exe", "Microsoft AntiSpyware"},
    {"agentsvr.exe", "Microsoft Agent Server"},
    {"pfwadmin.exe", "Kerio Personal Firewall"},
    {"fcssas.exe", "Microsoft Forefront Client Security State Assessment Service"},
    {"frzstate2k.exe", "Deep Freeze TM EDR"},
    {"avgwb.exe", "Grisoft AVG AntiVirus"},
    {"avnt.exe", "h+bedv datentechnik gmbh"},
    {"avkserv.exe", "g data software ag"},
    {"dao_log.exe", "McAfee DAO Logger"},
    {"avgupsvc.exe", "AVG"},
    {"avconfig.exe", "Avira"},
    {"scan32.exe", "McAfee Virusscan Enterprise"},
    {"upfile.exe", "Rising Antispyware"},
    {"dwhwizrd.exe", "Symantec"},
    {"frminst.exe", "mcafee"},
    {"dwengine.exe", "DrWeb"},
    {"mamutu.exe", "Mamutu"},
    {"etconsole3.exe", "EventTracker Console"},
    {"iedriver.exe", "urlblaze.com"},
    {"d_manage.exe", "d盾"},
    {"savfmsectrl.exe", "Symantec Mail Security"},
    {"avsched32.exe", "h+bedv"},
    {"pptbc.exe", "Protector Plus for Windows"},
    {"forcefield.exe", "ZoneAlarm ForceField"},
    {"avgrssvc.exe", "AVG"},
    {"vcrmon.exe", "viruschaser"},
    {"tcm.exe", "The Cleaner Registry and File Monitor"},
    {"ccschedulersvc.exe", "CA Internet Security Suite 2009"},
    {"kabackreport.exe", "Kingsoft"},
    {"pqv2isvc.exe", "Symantec"},
    {"pspf.exe", "Sygate Personal Firewall Pro"},
    {"zavaux.exe", "Zillya Antivirus"},
    {"sophos ui.exe", "Sophos杀毒"},
    {"setupguimngr.exe", "F-Secure Internet Security"},
    {"alupdate.exe", "Sophos Anti-Virus AutoUpdate"},
    {"v3lite.exe", "AhnLab V3 Light"},
    {"ccproxy.exe", "Symantec"},
    {"sched.exe", "avira(小红伞)"},
    {"mpfconsole.exe", "McAfee Personal Firewall"},
    {"avp32.exe", "Kaspersky"},
    {"acctmgr.exe", "Symantec"},
    {"kavmm.exe", "Kaspersky"},
    {"pccnt.exe", "TrendMicro PC-cillin"},
    {"ydservice.exe", "腾讯云-云镜主机安全"},
    {"stinger.exe", "McAfee Stinger"},
    {"ksafesvc.exe", "金山毒霸"},
    {"mgavrte.exe", "mcafee"},
    {"mcdetect.exe", "McAfee Security Centre Module"},
    {"autodown.exe", "antivirus autoupdater"},
    {"guard.exe", "AVG"},
    {"cleanpc.exe", "windows流氓软件清理大师"},
    {"drwinst.exe", "DrWeb"},
    {"360tray.exe", "360实时保护"},
    {"loggingserver.exe", "AVG Internet Security (64-bit)"},
    {"keenvalue.exe", "euniverse inc"},
    {"rstray.exe", "Rising Anti-Spyware"},
    {"snac.exe", "Symantec Network Access List"},
    {"cpdclnt.exe", "Symantec"},
    {"elogsvc.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"rnav.exe", "Symantec"},
    {"kis.exe", "Kaspersky"},
    {"kpf4ss.exe", "Sunbelt Personal Firewall 4"},
    {"rav.exe", "Rising AntiVirus"},
    {"sapissvc.exe", "Quick Heal Scanner"},
    {"mssense.exe", "windows defender"},
    {"avgvv.exe", "AVG"},
    {"era.exe", "ESET Remote Administrator"},
    {"deeprpcserver", "Deep Instinct NGAV"},
    {"svframe.exe", "SiliVaccine Antivirus"},
    {"ravservice.exe", "Rising AntiVirus"},
    {"ahnrpt.exe", "AhnLab Spy Zero"},
    {"nisoptui.exe", "Symantec"},
    {"nspupsvc.exe", "nprotect杀毒"},
    {"v3main.exe", "AhnLab V3 Light"},
    {"bullguardtray.exe", "BullGuard Internet Security"},
    {"sdtrayapp.exe", "Spyware_Doctor 5 from PC Tools"},
    {"avguard.exe", "Avira AntiVir"},
    {"avgupdln.exe", "AVG"},
    {"giantantispyware.exe", "GIANT AntiSpyware"},
    {"aflogvw.exe", "AhnLab Spy Zero"},
    {"cis.exe", "Comodo Internet Security"},
    {"ashchest.exe", "Avast"},
    {"fsbwsys.exe", "f-secure"},
    {"ravmon.exe", "Rising AntiVirus"},
    {"fsav530wtbyb.exe", "f-secure"},
    {"snichecksrv.exe", "Secret Net"},
    {"launcher.exe", "intercort systems"},
    {"ppmcativedetection.exe", "eTrust"},
    {"ashskpcc.exe", "Avast"},
    {"fspex.exe", "F-Secure Anti-Virus Updater"},
    {"up2date.exe", "Kaspersky Administration Kit"},
    {"dsa.exe", "Deep Security TM EDR"},
    {"360rp.exe", "360杀毒"},
    {"ras.exe", "Rising Antispyware"},
    {"securityhealthservice.exe", "windows defender"},
    {"cavrep.exe", "CA Internet Security Suite 2007"},
    {"pviewer.exe", "Process Explode process viewer"},
    {"firesvc.exe", "McAfee Desktop Firewall"},
    {"wssfcmai.exe", "LanAgent Monitoring"},
    {"lucoms.exe", "Symantec"},
    {"npfmntor.exe", "Symantec"},
    {"kavfsscs.exe", "Kaspersky script interception dispatcher service process"},
    {"firewallgui.exe", "PC Tools Firewall Plus"},
    {"kpf4gui.exe", "Sunbelt Personal Firewall 4"},
    {"nod32.exe", "Nod32"},
    {"avadmin.exe", "AVIRA Personal Edition Classic"},
    {"antiarp.exe", "AntiARP"},
    {"savfmseui.exe", "Symantec Mail Security"},
    {"pcscan.exe", "TrendMicro PC-cillin"},
    {"avgwb.dat", "AVG"},
    {"rssensor.exe", "McAfee Rogue System Sensor"},
    {"smoutlookpack.exe", "TrendMicro PC-cillin"},
    {"fwinst.exe", "AVIRA Personal Edition Classic"},
    {"nissrv.exe", "Microsoft Network Inspection System"},
    {"avgrsa.exe", "AVG Internet Security (64-bit)"},
    {"advchk.exe", "norton antivirus"},
    {"ksafetray.exe", "金山卫士"},
    {"scanfrm.exe", "Rising Anti-Virus"},
    {"v3sp.exe", "AhnLab V3 Light"},
    {"avgui.exe", "AVG Internet Security"},
    {"ashlogv.exe", "Avast"},
    {"fsav32.exe", "F-Secure Internet Security"},
    {"msssrv.exe", "McAfee Anti Spyware"},
    {"fcsms.exe", "Microsoft Forefront Client Security Management Service"},
    {"zavcore.exe", "Zillya Antivirus"},
    {"gcasinstallhelper.exe", "Microsoft AntiSpyware Helper Process"},
    {"safeservice.exe", "McAfee SAFe Common Technology"},
    {"loggetor.exe", "GoldenDolphin Chinese IDS"},
    {"avwebgrd.exe", "AVIRA Personal Edition Classic"},
    {"cfnotsrvd.exe", "CA eTrust Integrated Threat Management 8.1"},
    {"avgntmgr.exe", "avg"},
    {"unsecapp.exe", "Avast Internet Security"},
    {"ashavast.exe", "Avast"},
    {"psafesystray.exe", "psafe反病毒"},
    {"onlinent.exe", "Omniquad Total Security 3.0.0"},
    {"cpd.exe", "McAfee Firewall"},
    {"apvxdwin.exe", "Panda Internet Security"},
    {"paamsrv.exe", "Acronis Privacy Expert Suite"},
    {"drwebwin.exe", "DrWeb"},
    {"aupdrun.exe", "Agnirum Outpost Firewall"},
    {"ntcaagent.exe", "Huawei SACC Agent"},
    {"hwapi.exe", "McAfee Internet Security Suite"},
    {"mfetp.exe", "McAfee Threat Prevention Service"},
    {"svcharge.exe", "SiliVaccine Antivirus"},
    {"ccsystemreport.exe", "CA Internet Security Suite 2009"},
    {"neomonitor.exe", "NeoMonitor"},
    {"schdsrvc.exe", "Sophos Control Center"},
    {"mfw2en.exe", "myfreeinternetupdate"},
    {"ccsmagtd.exe", "CA eTrust Integrated Threat Management 8.1"},
    {"dpmra.exe", "Microsoft Security Center Data Protection Manager"},
    {"v3clnsrv.exe", "AhnLab"},
    {"sweepsrv.sys", "Sophos Anti-Virus"},
    {"fscuif.exe", "F-Secure Internet Security"},
    {"nisserv.exe", "Symantec"},
    {"aswregsvr.exe", "Avast"},
    {"redcloak.exe", "Dell SecureWorks Codename Redcloak"},
    {"a2free.exe", "a-squared free"},
    {"djsnetcn.exe", "Symantec"},
    {"psimreal.exe", "Panda Internet Security"},
    {"nsmdtr.exe", "Symantec"},
    {"npssvc.exe", "Symantec"},
    {"firewall.exe", "ashampoosoftware"},
    {"avgcmgr.exe", "AVG Internet Security (32-bit)"},
    {"vrvmail.exe", "VRV Security Software"},
    {"savfmsesjm.exe", "Symantec Mail Security"},
    {"kavfsgt.exe", "Kaspersky Anti-Virus management service process"},
    {"avgfws8.exe", "AVG"},
    {"mctool.exe", "mcafee"},
    {"redirsvc.exe", "McAfee Internet Security Suite"},
    {"fmon.exe", "FortiClient Host Security 3.0.459"},
    {"mcafeedatabackup.exe", "McAfee Internet Security Suite"},
    {"360websafe.exe", "360主机卫士"},
    {"kavfsrcn.exe", "Kaspersky Anti-Virus remote management process"},
    {"mfewch.exe", "McAfee Web Control Service"},
    {"smselog.exe", "Symantec"},
    {"afwserv.exe", "Avast Firewall Service"},
    {"pavfires.exe", "Panda Anti-Virus"},
    {"cclaw.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"fchelper64.exe", "Fortinet Smart Security"},
    {"dvp95.exe", "F-Secure"},
    {"tiaspn~1.exe", "Traffic Inspector 2.0"},
    {"evtarmgr.exe", "EventTracker by Prism Microsystems"},
    {"administrator.exe", "Entensys UserGate 5"},
    {"fshoster64.exe", "F-Secure Internet Security"},
    {"avira.exe", "小红伞杀毒"},
    {"sspservice.exe", "Sophos System Protection Service"},
    {"smsesp.exe", "Symantec"},
    {"avgwdsvc.exe", "AVG Anti-Virus"},
    {"avgidsagent.exe", "AVG 8.5/9.0 IDS"},
    {"aclntusr.exe", "Altiris Client"},
    {"dvp95_0.exe", "F-Secure"},
    {"gg.exe", "巨盾网游安全盾"},
    {"fsma32.exe", "F-Secure Internet Security"},
    {"mcods.exe", "McAfee Internet Security Suite"},
    {"kvmonxp_2.kxp", "Jiangmin AV and FW"},
    {"zatutor.exe", "ZoneAlarm Anti-Spyware"},
    {"savroam.exe", "Symantec"},
    {"baidusafetray.exe", "百度卫士"},
    {"olfsnt40.exe", "Symantec"},
    {"akrnl.exe", "ESET Smart Security"},
    {"tmbmsrv.exe", "pc-cillin趋势反病毒"},
    {"pavprot.exe", "Panda Anti-Virus"},
    {"nvcsched.exe", "Norman Ad-Aware SE Plus Antivirus 1.06r1 and Firewall 1"},
    {"cfgwiz.exe", "norton antivirus"},
    {"minilog.exe", "zone alarm"},
    {"iamserv.exe", "symantec"},
    {"qhactivedefense.exe", "360国际版"},
    {"vetmsg.exe", "CA AntiVirus VET Message Service"},
    {"avz.exe", "avz"},
    {"poproxy.exe", "Symantec"},
    {"avastui.exe", "Avast GUI"},
    {"ananwidget.exe", "墨者安全专家"},
    {"hipsdaemon.exe", "火绒安全软件"},
    {"swi_service.exe", "Sophos Anti-Virus"},
    { "caavguiscan.exe", "CA Internet Security Suite 2007"},
    { "inotask.exe", "CA eTrust Integrated Threat Management 8.1/CA Jinchen Kill"},
    { "sbserv.exe", "Symantec"},
    { "macompatsvc.exe", "McAfee Compat service"},
    { "routernt.exe", "Sophos Control Center"},
    { "avconsol.exe", "McAfee VirusScan Scheduler"},
    { "upschd.exe", "Omniquad Total Security 3.0.0"},
    { "avgfwsrv.exe", "AVG"},
    { "cpntsrv.exe", "Panda"},
    { "nsmdmon.exe", "TrendMicro"},
    { "sophoshealth.exe", "Sophos Health Service"},
    { "wtusystemsuport.exe", "AVG Internet Security (64-bit)"},
    { "drweb32w.exe", "DrWeb"},
    { "avgemcx.exe", "AVG Internet Security"},
    {"smc.exe", "Symantecor possibly Sygate"},
    { "kavsvc.exe", "Kaspersky"},
    { "processmonitor.exe", "sysinternals"}};

    }

}
